import { describe, expect, test } from 'claude-code/testing'

import { toKana } from './romaji'

// Ported from vime.nvim tests/vime/romaji_spec.lua (the default table's cases).
const CASES: readonly { name: string; cases: readonly (readonly [string, string])[] }[] = [
  {
    name: 'converts basic gojuon, dakuon and handakuon',
    cases: [
      ['aiueo', 'あいうえお'],
      ['ka', 'か'],
      ['ki', 'き'],
      ['ku', 'く'],
      ['ke', 'け'],
      ['ko', 'こ'],
      ['ga', 'が'],
      ['pa', 'ぱ'],
      ['za', 'ざ'],
      ['da', 'だ'],
      ['watashi', 'わたし'],
      ['wo', 'を'],
    ],
  },
  {
    name: 'converts youon and foreign sounds',
    cases: [
      ['kyou', 'きょう'],
      ['sha', 'しゃ'],
      ['sya', 'しゃ'],
      ['cha', 'ちゃ'],
      ['tya', 'ちゃ'],
      ['ja', 'じゃ'],
      ['jya', 'じゃ'],
      ['fa', 'ふぁ'],
      ['che', 'ちぇ'],
      ['tye', 'ちぇ'],
      ['fe', 'ふぇ'],
      ['jugyou', 'じゅぎょう'],
    ],
  },
  {
    name: 'converts the foreign-sound glide families generated by rule',
    cases: [
      ['fa', 'ふぁ'],
      ['fi', 'ふぃ'],
      ['fu', 'ふ'],
      ['fe', 'ふぇ'],
      ['fo', 'ふぉ'],
      ['va', 'ゔぁ'],
      ['vi', 'ゔぃ'],
      ['vu', 'ゔ'],
      ['ve', 'ゔぇ'],
      ['vo', 'ゔぉ'],
      ['tsa', 'つぁ'],
      ['tsi', 'つぃ'],
      ['tsu', 'つ'],
      ['tse', 'つぇ'],
      ['tso', 'つぉ'],
      ['wha', 'うぁ'],
      ['whi', 'うぃ'],
      ['whe', 'うぇ'],
      ['who', 'うぉ'],
      ['kwa', 'くぁ'],
      ['kwi', 'くぃ'],
      ['kwu', 'くぅ'],
      ['kwe', 'くぇ'],
      ['kwo', 'くぉ'],
      ['gwa', 'ぐぁ'],
      ['gwi', 'ぐぃ'],
      ['gwu', 'ぐぅ'],
      ['gwe', 'ぐぇ'],
      ['gwo', 'ぐぉ'],
      ['twa', 'とぁ'],
      ['twi', 'とぃ'],
      ['twu', 'とぅ'],
      ['twe', 'とぇ'],
      ['two', 'とぉ'],
      ['dwa', 'どぁ'],
      ['dwi', 'どぃ'],
      ['dwu', 'どぅ'],
      ['dwe', 'どぇ'],
      ['dwo', 'どぉ'],
      ['qa', 'くぁ'],
      ['qi', 'くぃ'],
      ['qe', 'くぇ'],
      ['qo', 'くぉ'],
      ['tha', 'てゃ'],
      ['thi', 'てぃ'],
      ['thu', 'てゅ'],
      ['the', 'てぇ'],
      ['tho', 'てょ'],
      ['dha', 'でゃ'],
      ['dhi', 'でぃ'],
      ['dhu', 'でゅ'],
      ['dhe', 'でぇ'],
      ['dho', 'でょ'],
      ['fya', 'ふゃ'],
      ['fyu', 'ふゅ'],
      ['fyo', 'ふょ'],
      ['vya', 'ゔゃ'],
      ['vyu', 'ゔゅ'],
      ['vyo', 'ゔょ'],
      ['ye', 'いぇ'],
      ['wu', 'う'],
      ['jyi', 'じぃ'],
      ['jye', 'じぇ'],
      ['lya', 'ゃ'],
      ['lyu', 'ゅ'],
      ['lyo', 'ょ'],
      ['xtsu', 'っ'],
      ['ltsu', 'っ'],
      ['xwa', 'ゎ'],
      ['lwa', 'ゎ'],
      ['xn', 'ん'],
    ],
  },
  {
    name: 'converts a doubled consonant to sokuon',
    cases: [
      ['tte', 'って'],
      ['kekka', 'けっか'],
      ['matcha', 'まっちゃ'],
      ['kippu', 'きっぷ'],
      ['issho', 'いっしょ'],
      ['tukatte', 'つかって'],
    ],
  },
  {
    name: 'resolves hatsuon n by look-ahead, nn always to ん',
    cases: [
      ['kanji', 'かんじ'],
      ['konnichiha', 'こんいちは'],
      ['konnnichiha', 'こんにちは'],
      ['onna', 'おんあ'],
      ['onnna', 'おんな'],
      ['annai', 'あんあい'],
      ['annnai', 'あんない'],
      ['tennki', 'てんき'],
      ['iitenki', 'いいてんき'],
      ['iitennki', 'いいてんき'],
      ['nn', 'ん'],
      ['n', 'ん'],
      ['honya', 'ほにゃ'],
      ['honnya', 'ほんや'],
      ['shinbun', 'しんぶん'],
      ["hon'ya", "ほん'や"],
    ],
  },
  {
    name: 'reads uppercase input as lowercase',
    cases: [
      ['Kyou', 'きょう'],
      ['KANJI', 'かんじ'],
    ],
  },
  {
    name: 'passes undefined characters through',
    cases: [['3ji', '3じ']],
  },
  {
    name: 'converts the long-vowel mark and passes other symbols through',
    cases: [
      ['-', 'ー'],
      ['su-pa-', 'すーぱー'],
      ['a!b', 'あ!b'],
    ],
  },
  {
    name: 'converts Japanese punctuation and brackets',
    cases: [
      [',', '、'],
      ['.', '。'],
      ['/', '・'],
      ['[', '「'],
      [']', '」'],
      ['a,i.', 'あ、い。'],
    ],
  },
  {
    name: 'converts the Google IME z-prefixed symbol shortcuts',
    cases: [
      ['zh', '←'],
      ['zj', '↓'],
      ['zk', '↑'],
      ['zl', '→'],
      ['z-', '〜'],
      ['z,', '‥'],
      ['z.', '…'],
      ['z/', '・'],
      ['z[', '『'],
      ['z]', '』'],
      ['za', 'ざ'],
      ['zya', 'じゃ'],
      ['kyouhazh', 'きょうは←'],
    ],
  },
  {
    name: 'converts the full target sentence',
    cases: [['kyouhaiitenkidane', 'きょうはいいてんきだね']],
  },
]

describe('toKana', () => {
  for (const { name, cases } of CASES) {
    test(name, () => {
      const actual = cases.map(([romaji]) => [romaji, toKana(romaji)])

      expect(actual).toEqual(cases)
    })
  }

  test('keeps a trailing single n as n while the input is in progress, and resolves it otherwise', () => {
    const actual = [
      toKana('n', true),
      toKana('kan', true),
      toKana('nn', true),
      toKana('kanji', true),
      toKana('kan'),
      toKana('kan', false),
    ]

    expect(actual).toEqual(['n', 'かn', 'ん', 'かんじ', 'かん', 'かん'])
  })
})
